### PR TITLE
Use lodash v3

### PR DESCRIPTION
**Pull request by seethemhigh**
Hello. This is a PR for #21 . I think this can be merged in since tests are passing.
Thanks.

### CODE REVIEW

**Comment by guirong** [comment]
watching this problem

**Comment by xsoameix** [comment]
+1

**Comment by YuliaTsareva** [comment]
+1

**Comment by ricardogomes** [comment]
+1

**Comment by SgtPooki** [comment]
@seethemhigh, The build is only failing on node version 0.8, and [only because of a version mismatch](https://travis-ci.org/cowboy/node-globule/jobs/93179521). I would recommend changing the version to ~3.10.1 though.

Check out https://github.com/npm/npm/issues/4849 for more information about the 0.8 failure.

After updating the version, it should be good to Ship.

**Comment by SgtPooki** [comment]
@cowboy Can you update your node v0.8 for Travis CI to something like the following: https://github.com/npm/npm/issues/6246#issuecomment-57911124

If that doesn't work, the thread contains more information about resolving this issue.

**Comment by seethemhigh** [comment]
@SgtPooki, thanks for the hint. I'm going to change the version.

**Comment by SgtPooki** [comment]
Related to https://github.com/gulpjs/glob-watcher/issues/23

**Comment by seethemhigh** [comment]
Now it's yelling at 'grunt-legacy-log-utils'.

**Comment by jdalton** [comment]
Is this just to remove a deprecation message or are builds failing. If its builds failing what's the setup that they're failing on, e.g. powershell or something else?

**Comment by JJ** [comment]
Just checking. Also related to #23

**Comment by yaycmyk** [comment]
Included this in my rollup PR: https://github.com/cowboy/node-globule/pull/26

**Comment by shama** [comment]
Fixed by bd05d83e5965c38060b85f7227491650f8707436 thanks!

**Comment by jorrit** [comment]
Lodash 4 was released after this PR was opened. Is it an idea to upgrade to LD 4 while we're upgrading anyway?

**Comment by jorrit** [comment]
Never mind, I see that exactly that was done in another commit, thanks @shama !

**Comment by shama** [comment]
I'll have a release out soon too but want to fix this test https://github.com/cowboy/node-globule/blob/master/test/globule_test.js#L305 as it's failing on Windows due to the `path.join` that `prefixBase` does.

**Comment by jorrit** [comment]
@shama please see #32

**Pull request closed without merging**
