### PR TITLE
lodash is a huge library, which everyone is trying to avoid importing…

### PR DESCRIPTION
**Pull request by EsrefDurna**
… fullly, the suggested way and easy way to load is either use lodash/function or install specifis lodash library, such as npm lodash.Isarray library, for now its better to keep the lodash dependency, however it could be better if we reduce the number of functions that we using from lodash, and eventually its way much better to switch es6 completey (we can't now because of the node target)

added npmignore file,
added package-lock.json file

### CODE REVIEW

**Comment by shama** [comment]
What is the actual difference in size between using `lodash` and these libraries individually?

**Comment by EsrefDurna** [comment]
https://twitter.com/dan_abramov/status/605691126549508096?lang=en

**Comment by EsrefDurna** [comment]
that tweet have a nice conversation around this issue,

**Comment by EsrefDurna** [comment]
and about what's the difference is 
instead of loading all 200 functions into memory, you will load 10 individual functions

**Comment by shama** [comment]
I'm curious about the actual numbers. 300 bytes versus 1000 bytes determines how much this is worth the bother. That tweet is mostly concerned about client side, which this library is not.

**Comment by EsrefDurna** [comment]
You are right, let me run comparison tests

**Comment by EsrefDurna** [comment]
you are right, not a performance change, let me work on it to find if there is another problem

**Comment by shama** [comment]
FWIW, I think removing some of the unneeded lodash functions would be good. The code was originally wrote for ES3 which we could probably drop support for now.

**Pull request closed without merging**
